language: cpp

addons:
    apt:
        packages:
            - mesa-common-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libxext-dev
            - g++-5

script:
  - cmake .
  - cmake --build . -- -j2
